version: '3.3'
services:
  database:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_USER: 'APIUser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'DBProjet2'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  api:
    image: ghcr.io/amt-14/gamificationapi_image:latest
    ports:
      - '8080:8080'
    depends_on: 
      - database
    environment:
      MYSQL_HOST: 'database'
    command: ["./wait-for-it.sh", "database:3306"]

