openapi: '3.0.3'
info:
  version: '0.2.0'
  title: Gamification
  description: we're trying to make it work
security:
  #  - bearerAuth: []
  - apiKeyAuth: []
paths:
  /score:
    post:
      description: create score
      operationId: createScore
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Score'
      responses:
        '201':
          description: updated
  /score/{id}:
    get:
      description: get the score
      operationId: getScore
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
            description: success
            content:
              'application/json':
                schema:
                    $ref: '#/components/schemas/Score'
  /fruits:
    post:
      description: create a fruit
      operationId: createFruit
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Fruit'
      responses:
        '201':
          description: created
    get:
      description: get the list of all fruits
      operationId: getFruits
      responses:
        '200':
          description: success
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fruit'
  /fruits/{id}:
    get:
      description: get one fruit, by id
      operationId: getFruit
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Fruit'
components:
  securitySchemes:
    #    bearerAuth:            # arbitrary name for the security scheme
    #      type: http
    #      scheme: bearer       # warning: it HAS TO be a lowercase b for the swagger ui version used in springfox
    #      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    Score:
      type: object
      properties:
        value:
          type: Integer
    Fruit:
      type: object
      properties:
        kind:
          type: string
        colour:
          type: string
        size:
          type: string
        weight:
          type: string
        expirationDate:
          type: string
          format: date
          nullable: false
        expirationDateTime:
          type: string
          format: date-time